### PR TITLE
workflows/tests: run brew portable-package on Linux.

### LINKED ISSUE #87: Run brew portable-package on Linux CI
See:
https://github.com/Homebrew/homebrew-portable-ruby/blob/4fe159fc08e2dffb17146c6938ce162075d60fcb/.github/workflows/tests.yml#L40-L43

Currently this doesn't do anything but it should be configured to use this repository as expected.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Fixes #87.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@sjackman Still misbehaving, mind taking a look?

**Comment by sjackman** [comment]
```
==> /home/linuxbrew/.linuxbrew/bin/brew linkage homebrew/portable-ruby/portable-ruby
Error: homebrew/portable-ruby/portable-ruby: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </Homebrew libraries/> expected to not match
System libraries:
  /lib64/ld-linux-x86-64.so.2
Homebrew libraries:
  /home/linuxbrew/.linuxbrew/lib/libc.so.6 (glibc)
  /home/linuxbrew/.linuxbrew/lib/libcrypt.so.1 (glibc)
  /home/linuxbrew/.linuxbrew/lib/libdl.so.2 (glibc)
  /home/linuxbrew/.linuxbrew/lib/libm.so.6 (glibc)
  /home/linuxbrew/.linuxbrew/lib/libpthread.so.0 (glibc)
  /home/linuxbrew/.linuxbrew/lib/libutil.so.1 (glibc)
```
https://github.com/Homebrew/homebrew-portable-ruby/pull/88/checks?check_run_id=226608008#step:7:437

https://github.com/Homebrew/homebrew-portable-ruby/blob/fe8137a9d63ba42e0b104c9393b5b8b779e9bec4/Abstract/portable-formula.rb#L30-L31

`brew test portable-ruby` asserts that the keg is not linked against any brewed libraries. It's failing because it's detecting that it's linked against the brewed `glibc`. It looks like some bit rot has crept in. The brew `brew portable-package` command should not installed the brewed `glibc`.

**Comment by MikeMcQuaid** [comment]
> `brew test portable-ruby` asserts that the keg is not linked against any brewed libraries. It's failing because it's detecting that it's linked against the brewed `glibc`. It looks like some bit rot has crept in. The brew `brew portable-package` command should not installed the brewed `glibc`.

@sjackman Could you prioritise taking a look at this? Having no Linux CI for this repository is very non-ideal considering we're going to be building 2.6.x for Catalina within a month.

**Comment by sjackman** [comment]
Yes, I can take a look at it.

**Comment by MikeMcQuaid** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-portable-ruby/pull/89

**Pull request closed without merging**
