### PR TITLE
portable-ruby: Add mirrors for the patches

### PR DESCRIPTION
**Pull request by sjackman**
For older versions of curl, work around the error:
```
curl: (35) error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
```

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@sjackman I don't think this is the right solution here. `brew install curl` is already configured to ensure it's built to be able to access GitHub. Does `brew install curl` not fix this?

**Comment by MikeMcQuaid** [comment]
@sjackman May also want to consider adding stripped bottles in here?

**Comment by sjackman** [comment]
```
brew install curl is already configured to ensure it's built to be able to access GitHub. Does brew install curl not fix this?
```
`/usr/bin/curl` on CentOS 5 is not able to access GitHub, since it gives the above error `tlsv1 alert protocol version`. `brew install curl` may fix this issue if it installs `curl` from bottle rather than from source. You prefer that solution?

**Comment by MikeMcQuaid** [comment]
> /usr/bin/curl on CentOS 5 is not able to access GitHub, since it gives the above error tlsv1 alert protocol version

It shouldn't need to access GitHub; only `git` does for the installation Homebrew installation and `brew install curl` should not need to use HTTPS to do so.



> @sjackman May also want to consider adding stripped bottles in here?

To contradict myself: let's leave these as-is; the debug symbols are present on macOS and have been useful in (rare) Homebrew Ruby crashes in the past.

**Comment by MikeMcQuaid** [comment]
> brew portable-package ruby needs HTTPS access to GitHub to download the two patches.

Yes but if `brew install curl` has already been run: why can it not use that `curl` instead?

**Comment by sjackman** [comment]
`brew install curl` has not yet been run. Recall: `brew install curl` may fix this issue if it installs curl from bottle rather than from source. You prefer that solution?

**Comment by sjackman** [comment]
I was avoiding installing any brewed packages to avoid any possible interactions between the `foo` and `portable-foo` packages. My caution may not be warranted, if the `portable-foo` packages are sufficiently isolated from the `foo` packages.

**Comment by MikeMcQuaid** [comment]
> My caution may not be warranted, if the portable-foo packages are sufficiently isolated from the foo packages.

They are sufficiently isolated, `brew portable-package` and CI test this isolation and this is the same workflow (`brew install curl`) as required on Leopard to build the Ruby there.

**Comment by sjackman** [comment]
Feel free to close this issue.

**Comment by MikeMcQuaid** [comment]
Cool, thanks @sjackman.

**Pull request closed without merging**
