### PR TITLE
portable-ruby 2.3.7

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Also update all dependencies and fix their descriptions.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Looks like the Mac build pulled in an old revision of automake. The issue it's complaining about was [removed in March](https://github.com/Homebrew/homebrew-core/commit/1e1a871fd9a35d618f5fd8b486ad3a3817feb08a).

```
==> Installing portable-ruby from homebrew/portable-ruby
Error: Calling 'depends_on ... => :run' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/automake.rb:18:in `<class:Automake>'
```

**Comment by justjake** [comment]
Thank you @MikeMcQuaid for patching portable-ruby, and thank you to apple for bumping your ruby version

**Comment by MikeMcQuaid** [comment]
@justjake and thank you for the kind words, I genuinely appreciate them ❤️

**Comment by sjackman** [comment]
I've built and uploaded the `portable-ruby` bottle for ARM (Raspberry Pi).
https://bintray.com/homebrew/bottles-portable-ruby/portable-ruby/2.3.7#files
https://github.com/Homebrew/homebrew-portable-ruby/releases/tag/2.3.7

I never managed to successfully build the `dbm` module for Ruby 2.3.7 (it was successfully built for 2.3.3). Good riddance to `dbm`. Long live JSON!

**Pull request merged**
