### PR TITLE
allow test to run for ruby3 branch

### PR DESCRIPTION
**Pull request by SMillerDev**
This should allow the build for ARM to succeed at least.

### CODE REVIEW

**Review by mistydemeo — APPROVED** [review]

**Comment by SMillerDev** [comment]
@Bo98 ?

**Comment by Bo98** [comment]
Sorry didn't see this.

This is fine, though I consider Portable Ruby 3 pretty much dead for now given the desire to stay on 2.6 for as long as Apple ship it (which could be years for all we know - Apple have a lot of internal stuff using it to deal with). I guess we'll see in a month's time.

I'd also like to not force users to have to `bundle install`, but this is fine as a temp fix for this branch only.

**Comment by Bo98** [comment]
Yeah this is on the cards to revisiting shortly.

I would say first step that can be done here is enabling `brew` CI to run on Ruby 3 (using `ruby/setup-ruby`). I can open a PR for that. Eventually that will switch to Portable Ruby, but that will help us make sure we're not introducing regressions in between the times I've been testing on Ruby 3, which is only every so often.

**Comment by MikeMcQuaid** [comment]
> Something that can be done now is enabling `brew` CI to run on Ruby 3 (using `ruby/setup-ruby`). I can open a PR for that. Eventually that will switch to Portable Ruby of course, but adjusting CI now could help us make sure we're not introducing regressions in between the times I've been testing on Ruby 3, which is only every so often. We can also wait though for Portable Ruby - I don't mind either way.

Works for me 👍🏻

We should probably keep at least one basic test on Ruby 2 for now. Perhaps we could switch only Linux over to Ruby 3 for now and use Ruby 2 for macOS until we ship portable Ruby there?

**Comment by MikeMcQuaid** [comment]
> There's one patch I will also look at upstreaming, though I don't consider that a blocker.

Would like to block on it being submitted upstream before we release portable Ruby but don't think it needs merged.

**Comment by Bo98** [comment]
> > There's one patch I will also look at upstreaming, though I don't consider that a blocker.
> 
> Would like to block on it being submitted upstream before we release portable Ruby but don't think it needs merged.

Yeah sorry, should have clarified it that way.

**Comment by Bo98** [comment]
Are we game to start vendoring Ruby 3 gems now? That's the main issue right now as you cannot run brew without basic gems like activesupport installed.

**Comment by MikeMcQuaid** [comment]
> Yeah was thinking a matrix of Ruby 3 and Ruby 2 of course - absolutely not a complete switch to Ruby 3 yet.

Sounds good 👍🏻. 

> Are we game to start vendoring Ruby 3 gems now? That's the main issue right now as you cannot run brew without basic gems like activesupport installed.

I'd like to avoid vendoring more than one version in the repository. For now, it should be expected you'll need to run `brew install-bundler-gems` manually or automatically to install the relevant gems which should be hidden by `.gitignore`.

**Comment by Bo98** [comment]
There's symlink magic we could also do but I'll need to try that out in practice beforehand.

I think for now we won't do separate Ruby 2 and Ruby 3 lockfiles. We'll lock everything based on Ruby 2.6 until we've fully switched as it just makes everything so much simpler. Then we will update everything.

**Comment by MikeMcQuaid** [comment]
> Except you can't because these things get required before you even reach CLI parsing. Bit of a chicken egg problem right now, unless we move the whole thing to a plain Ruby script that gets invoked from shell.

I think it could be moved to Bash, honestly, as it's essentially just doing `bundle check && bundle install`. This could be as a separate `brew install-bundler-gems-bash` hidden command at first if we wanted to maintain all the existing easier-in-Ruby behaviours. 

The logic is straightforward for the vendored gems (which don't have native components), though: if they are missing, `cd Library/Homebrew && bundle install`.

**Comment by MikeMcQuaid** [comment]
> > The logic is straightforward for the vendored gems (which don't have native components), though: if they are missing, `cd Library/Homebrew && bundle install`.
> 
> Not quite - or at least not yet. What I will do is separate all non-vendored gems into groups which would make it so that will only do vendored gems and no native stuff.

I think that's a "nice to have". For now when Ruby 3 is only being used by developers/in CI (which I expect to be the case until we move everyone to Portable Ruby 3): doing a plain `bundle install` really should be sufficient, no?

**Comment by Bo98** [comment]
Sure, in terms of that yeah. Though I imagine there'll be some steps in between opt-in/CI and enabling for everyone?

**Pull request merged**
