### PR TITLE
portable-ruby: Add patch PR link

### PR DESCRIPTION
**Pull request by p-linnane**
As requested in https://github.com/Homebrew/homebrew-portable-ruby/pull/230#discussion_r1701509444

### CODE REVIEW

**Review by SMillerDev — APPROVED** [review]

**Comment by SMillerDev** [comment]
Should we apply this patch to our plain ruby too?

**Comment by p-linnane** [comment]
Let's see what @Bo98 thinks.

**Comment by Bo98** [comment]
Sure, though no guarantee when it can be removed like we normally have with other core patches. Maybe also worth monitoring Intel CI over the weekend after I roll this out to see if it works.

**Comment by MikeMcQuaid** [comment]
Thanks @p-linnane!

**Pull request merged**
