### PR TITLE
portable-openssl: update mirror

### PR DESCRIPTION
**Pull request by Bo98**
Homebrew/mirror will cease tomorrow.

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]

**Comment by Bo98** [comment]
Not sure what the preference is for dealing with DL3059. Do we even use layer caching? (We currently ignore DL3008 so I assume not.)

**Comment by MikeMcQuaid** [comment]
@Bo98 Makes sense 👍🏻

**Comment by Bo98** [comment]
Which bit makes sense? I'll just ignore DL3059 and someone else can make it their problem if they think it needs addressing :-)

**Comment by MikeMcQuaid** [comment]
> I'll just ignore DL3059 and someone else can make it their problem if they think it needs addressing

Yup, thanks ❤️

**Pull request merged**
