### PR TITLE
docker/Dockerfile.x86_64: wheezy moved to archive

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Still failing unfortunately: https://dev.azure.com/Homebrew/Homebrew/_build/results?buildId=6643

**Comment by sjackman** [comment]
Related issue https://github.com/debuerreotype/docker-debian-artifacts/issues/65

**Comment by sjackman** [comment]
Should hopefully be fixed now.

**Comment by MikeMcQuaid** [comment]
Thanks @sjackman!

**Pull request merged**
