### PR TITLE
Portable Ruby 3.3.1

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Maybe we want 3.2 instead but 3.3 seems reasonable for us to at least try out.

Also remove unneeded dependencies.

Closes https://github.com/Homebrew/homebrew-portable-ruby/pull/189

### CODE REVIEW

**Comment by Bo98** [comment]
libedit I think can be deleted entirely if we're definitely going for 3.3.

**Comment by MikeMcQuaid** [comment]
> We should decide what the update strategy here is going forward. Last time the idea was x.(y - 1).z on Aprils. Maybe the strategy now is latest x.y.z when z >= 1.

Yeh, Ruby minor releases are stable enough now that 3.3.1 seems pretty rock solid in my use elsewhere.

I like the idea of x.y.(z >=1) as you've said (and ideally start tracking the patch releases too).

**Comment by MikeMcQuaid** [comment]
> libedit and ncurses(?) I think can be deleted entirely if we're definitely going for 3.3.

Done!

**Comment by Bo98** [comment]
> I like the idea of x.y.(z >=1) as you've said (and ideally start tracking the patch releases too).

This is nice since I was wanting to add autobump and something like this can be nicely algorithmically picked in a livecheck block.

**Review by Bo98 — APPROVED** [review]
`MJIT_CC` I think can be removed too sine MJIT is no more but LGTM otherwise

**Comment by MikeMcQuaid** [comment]
> `MJIT_CC` I think can be removed too

Good idea, done!

**Comment by carlocab** [comment]
`brew tests` is looking good for me with 3.3.1. Only failure seems unrelated:
```
Failures:

  1) Cask::Artifact::App install_phase when the target already exists given the force option target is user-owned but contains read-only files overwrites the existing app
     Failure/Error: let(:install_phase) { app.install_phase(command:, adopt:, force:) }

     ErrorDuringExecution:
       Failure while executing; `/usr/bin/env touch /private/tmp/homebrew-tests-20240515-52974-mimh8r/cask-appdir/Caffeine.app/.homebrew-write-test` exited with 1. Here's the output:
       touch: /private/tmp/homebrew-tests-20240515-52974-mimh8r/cask-appdir/Caffeine.app/.homebrew-write-test: Permission denied
     # ./system_command.rb:352:in `assert_success!'
     # ./system_command.rb:75:in `run!'
     # ./system_command.rb:40:in `run'
     # ./test/support/helper/cask/never_sudo_system_command.rb:8:in `run'
     # ./system_command.rb:44:in `run!'
     # ./cask/quarantine.rb:236:in `app_management_permissions_granted?'
     # ./cask/artifact/moved.rb:107:in `move'
     # ./cask/artifact/moved.rb:17:in `install_phase'
     # ./test/cask/artifact/app_spec.rb:13:in `block (2 levels) in <top (required)>'
     # ./test/cask/artifact/app_spec.rb:185:in `block (7 levels) in <top (required)>'
     # ./test/cask/artifact/app_spec.rb:185:in `block (6 levels) in <top (required)>'
     # ./test/support/helper/spec/shared_context/homebrew_cask.rb:64:in `block (2 levels) in <top (required)>'
```

**Review by carlocab — APPROVED** [review]

**Comment by MikeMcQuaid** [comment]
Thanks for help @carlocab and @Bo98!

**Pull request merged**
